version: '3.8'

services:

  php_apache:
    container_name: php_apache
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    volumes:
      - ./api:/var/www/html

    ports:
      - 8000:80

  mysql_db:
    container_name: mysql_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bg9FrdmCk*dLGIre
      MYSQL_DATABASE: docfav_db
      MYSQL_USER: docfav_usr
      MYSQL_PASSWORD: Bg9FrdmCk*dLGIre
    ports:
      - "9906:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  mysql_data:
